//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CODEDTL
    {
        public string TYPECD { get; set; }
        public string CODECD { get; set; }
        public string CODENAME { get; set; }
        public string FIXEDYN { get; set; }
        public decimal PAYAMOUNT { get; set; }
        public string FATHERCD { get; set; }
        public string Remark { get; set; }
        public Nullable<decimal> TempletID1 { get; set; }
        public Nullable<decimal> TempletID2 { get; set; }
        public string HolidayInclude { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> MaxLeave { get; set; }
        public Nullable<decimal> MaxPay { get; set; }
        public string Apportion { get; set; }
        public Nullable<decimal> TempletID3 { get; set; }
        public Nullable<decimal> MinUnit { get; set; }
        public string ChineseName2 { get; set; }
        public string EnglishName2 { get; set; }
    }
}
