//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactHistoy
    {
        public int ID { get; set; }
        public string Ref_Department_ID { get; set; }
        public string Ref_Department_Name { get; set; }
        public string WinningPeriod { get; set; }
        public string WinningNum { get; set; }
        public string OrderNum { get; set; }
        public string TargetEmail { get; set; }
        public string WinningLevel { get; set; }
        public System.DateTime SendTime { get; set; }
        public string Status { get; set; }
        public string Messages { get; set; }
    }
}
